name: time-tracking-dashboard

networks:
  time-tracking-dashboard-network:

services:
  ttd-frontend:
    build:
      context: ./app-ui
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    # volumes:
    #   - ./app-ui:/app
    depends_on:
      - ttd-backend
    networks:
      - time-tracking-dashboard-network

  ttd-backend:
    build:
      context: ./app-backend
      dockerfile: Dockerfile.backend
    env_file:
      - path: ./app-backend/.env.local
    ports:
      - "3000:3000"
    volumes:
      - ./app-backend:/app
    depends_on:
      - ttd-db
    networks:
      - time-tracking-dashboard-network

  ttd-db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - path: ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - time-tracking-dashboard-network
