-- Seed tasks (new schema): (user_id, title, category, timeframe, previous_duration, duration)
-- duration is an INTEGER in hours; previous_duration is NULL
INSERT INTO tasks (user_id, title, category, timeframe, previous_duration, duration)
VALUES
(1, 'Cycling Session', 'exercise', 'daily', NULL, 2),
(1, 'Board Game Night', 'play', 'daily', NULL, 1),
(1, 'Do Coding Kata', 'study', 'daily', NULL, 1),
(1, 'Family Time', 'social', 'daily', NULL, 1),
(1, 'Bug Fix Triage', 'work', 'daily', NULL, 1),
(1, 'Journaling', 'self-care', 'daily', NULL, 1),
(1, 'Creative Writing', 'play', 'weekly', NULL, 2),
(1, 'Yoga Flow', 'exercise', 'weekly', NULL, 4),
(1, 'System Design Notes', 'study', 'weekly', NULL, 3),
(1, 'Sprint Demo Prep', 'work', 'weekly', NULL, 3),
(1, 'Reading for Fun', 'self-care', 'weekly', NULL, 2),
(1, 'Call a Friend', 'social', 'weekly', NULL, 2),
(1, 'Power Nap', 'self-care', 'monthly', NULL, 4),
(1, 'Core Routine', 'exercise', 'monthly', NULL, 10),
(1, 'Photography Walk', 'play', 'monthly', NULL, 4),
(1, 'Call a Friend', 'social', 'monthly', NULL, 12),
(1, 'Sprint Demo Prep', 'work', 'monthly', NULL, 8),
(1, 'Read Dev Blog', 'study', 'monthly', NULL, 24),
(2, 'Morning Run', 'exercise', 'daily', NULL, 2),
(2, 'Backlog Grooming', 'work', 'daily', NULL, 1),
(2, 'Reading for Fun', 'self-care', 'daily', NULL, 2),
(2, 'Jam on Piano', 'play', 'daily', NULL, 1),
(2, 'System Design Notes', 'study', 'daily', NULL, 1),
(2, 'Family Time', 'social', 'daily', NULL, 1),
(2, 'Community Event', 'social', 'weekly', NULL, 3),
(2, 'Bug Fix Triage', 'work', 'weekly', NULL, 6),
(2, 'Cycling Session', 'exercise', 'weekly', NULL, 2),
(2, 'Meal Prep', 'self-care', 'weekly', NULL, 3),
(2, 'Casual Streaming', 'play', 'weekly', NULL, 1),
(2, 'Write Study Summary', 'study', 'weekly', NULL, 2),
(2, 'Coffee Chat', 'social', 'monthly', NULL, 6),
(2, 'Power Nap', 'self-care', 'monthly', NULL, 8),
(2, 'Board Game Night', 'play', 'monthly', NULL, 6),
(2, 'Long Walk', 'exercise', 'monthly', NULL, 6),
(2, 'Write Study Summary', 'study', 'monthly', NULL, 24),
(2, 'Sprint Demo Prep', 'work', 'monthly', NULL, 12),
(3, 'Refactor Legacy Module', 'work', 'daily', NULL, 1),
(3, 'Board Game Night', 'play', 'daily', NULL, 1),
(3, 'Meal Prep', 'self-care', 'daily', NULL, 1),
(3, 'Swim Laps', 'exercise', 'daily', NULL, 1),
(3, 'Project Lab Time', 'study', 'daily', NULL, 2),
(3, 'Family Time', 'social', 'daily', NULL, 1),
(3, 'Bug Fix Triage', 'work', 'weekly', NULL, 1),
(3, 'Video Game Session', 'play', 'weekly', NULL, 3),
(3, 'Read Architecture Book', 'study', 'weekly', NULL, 4),
(3, 'Volunteer Hour', 'social', 'weekly', NULL, 2),
(3, 'Reading for Fun', 'self-care', 'weekly', NULL, 4),
(3, 'Core Routine', 'exercise', 'weekly', NULL, 1),
(3, 'HIIT Workout', 'exercise', 'monthly', NULL, 12),
(3, 'Bug Fix Triage', 'work', 'monthly', NULL, 12),
(3, 'Coffee Chat', 'social', 'monthly', NULL, 4),
(3, 'Watch a Movie', 'play', 'monthly', NULL, 12),
(3, 'Review Flashcards', 'study', 'monthly', NULL, 8),
(3, 'Meal Prep', 'self-care', 'monthly', NULL, 10),
(4, 'Morning Run', 'exercise', 'daily', NULL, 1),
(4, 'Coffee Chat', 'social', 'daily', NULL, 1),
(4, 'Jam on Piano', 'play', 'daily', NULL, 2),
(4, 'Read Architecture Book', 'study', 'daily', NULL, 1),
(4, 'Plan the Week', 'self-care', 'daily', NULL, 1),
(4, 'Deep Work Block', 'work', 'daily', NULL, 2),
(4, 'Pair Programming', 'work', 'weekly', NULL, 2),
(4, 'Core Routine', 'exercise', 'weekly', NULL, 2),
(4, 'Project Lab Time', 'study', 'weekly', NULL, 1),
(4, 'Tidy Desk', 'self-care', 'weekly', NULL, 3),
(4, 'Date Night', 'social', 'weekly', NULL, 1),
(4, 'Jam on Piano', 'play', 'weekly', NULL, 6),
(4, 'Morning Run', 'exercise', 'monthly', NULL, 12),
(4, 'System Design Notes', 'study', 'monthly', NULL, 6),
(4, 'Deep Work Block', 'work', 'monthly', NULL, 8),
(4, 'Meditation', 'self-care', 'monthly', NULL, 24),
(4, 'Sketch & Doodle', 'play', 'monthly', NULL, 10),
(4, 'Family Time', 'social', 'monthly', NULL, 6);