INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Work', 'Daily', 7);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Work', 'Weekly', 36);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Work', 'Monthly', 128);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Play', 'Daily', 2);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Play', 'Weekly', 8);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Play', 'Monthly', 29);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Study', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Study', 'Weekly', 7);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Study', 'Monthly', 19);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Exercise', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Exercise', 'Weekly', 5);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Exercise', 'Monthly', 18);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Social', 'Daily', 3);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Social', 'Weekly', 10);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Social', 'Monthly', 23);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Self Care', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Self Care', 'Weekly', 2);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (1, 'Self Care', 'Monthly', 11);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Work', 'Daily', 7);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Work', 'Weekly', 36);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Work', 'Monthly', 128);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Play', 'Daily', 2);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Play', 'Weekly', 8);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Play', 'Monthly', 29);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Study', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Study', 'Weekly', 7);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Study', 'Monthly', 19);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Exercise', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Exercise', 'Weekly', 5);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Exercise', 'Monthly', 18);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Social', 'Daily', 3);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Social', 'Weekly', 10);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Social', 'Monthly', 23);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Self Care', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Self Care', 'Weekly', 2);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (2, 'Self Care', 'Monthly', 11);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Work', 'Daily', 7);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Work', 'Weekly', 36);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Work', 'Monthly', 128);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Play', 'Daily', 2);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Play', 'Weekly', 8);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Play', 'Monthly', 29);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Study', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Study', 'Weekly', 7);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Study', 'Monthly', 19);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Exercise', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Exercise', 'Weekly', 5);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Exercise', 'Monthly', 18);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Social', 'Daily', 3);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Social', 'Weekly', 10);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Social', 'Monthly', 23);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Self Care', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Self Care', 'Weekly', 2);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (3, 'Self Care', 'Monthly', 11);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Work', 'Daily', 7);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Work', 'Weekly', 36);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Work', 'Monthly', 128);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Play', 'Daily', 2);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Play', 'Weekly', 8);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Play', 'Monthly', 29);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Study', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Study', 'Weekly', 7);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Study', 'Monthly', 19);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Exercise', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Exercise', 'Weekly', 5);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Exercise', 'Monthly', 18);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Social', 'Daily', 3);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Social', 'Weekly', 10);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Social', 'Monthly', 23);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Self Care', 'Daily', 1);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Self Care', 'Weekly', 2);
INSERT INTO tasks (user_id, title, category, previous_time_spent_minutes) VALUES (4, 'Self Care', 'Monthly', 11);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (1, 5);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (2, 32);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (3, 103);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (4, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (5, 10);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (6, 23);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (7, 0);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (8, 4);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (9, 13);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (10, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (11, 4);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (12, 11);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (13, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (14, 5);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (15, 21);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (16, 0);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (17, 2);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (18, 7);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (19, 5);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (20, 32);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (21, 103);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (22, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (23, 10);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (24, 23);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (25, 0);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (26, 4);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (27, 13);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (28, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (29, 4);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (30, 11);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (31, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (32, 5);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (33, 21);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (34, 0);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (35, 2);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (36, 7);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (37, 5);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (38, 32);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (39, 103);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (40, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (41, 10);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (42, 23);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (43, 0);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (44, 4);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (45, 13);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (46, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (47, 4);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (48, 11);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (49, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (50, 5);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (51, 21);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (52, 0);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (53, 2);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (54, 7);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (55, 5);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (56, 32);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (57, 103);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (58, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (59, 10);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (60, 23);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (61, 0);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (62, 4);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (63, 13);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (64, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (65, 4);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (66, 11);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (67, 1);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (68, 5);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (69, 21);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (70, 0);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (71, 2);
INSERT INTO task_entries (task_id, time_spent_minutes) VALUES (72, 7);