name: Features Git Flow
on:
  pull_request:
    branches: ["develop"]
    types:
      - closed
permissions:
  contents: write
  pull-requests: write
env:
  USERNAME: ${{ secrets.BOT_USERNAME }}
  EMAIL: ${{ secrets.BOT_EMAIL }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0
